/* ========================================
 *
 * Copyright YOUR COMPANY, THE YEAR
 * All Rights Reserved
 * UNPUBLISHED, LICENSED SOFTWARE.
 *
 * CONFIDENTIAL AND PROPRIETARY INFORMATION
 * WHICH IS THE PROPERTY OF your company.
 *
 * ========================================
*/
#include <project.h>
#include "main.h"

/*******************************************************************************
* Variable Declaration
********************************************************************************/
volatile uint8 disconnect_flag = 0x0; 
volatile uint8 ble_flag = 0x0;
uint8 msg_buffer[20] = {0}; 



/*******************************************************************************
* Function Name: EnableStop
********************************************************************************
*
* Summary:
*  Performs the stop of the BLE Chip
*
* Parameters:
*       Void
*
* Return:
*  None
*
*******************************************************************************/
static void EnableStop(void)
{
    DebugCode("SHREY: Turning Off the Chip");
    UART_Dbg_Stop(); 
    CySysPmStop();
}
/*******************************************************************************
* Function Name: StackEventHandler
********************************************************************************
*
* Summary:
*  This is an event callback function to receive events from the BLE Component.
*
* Parameters:
*  uint8 event:       Event from the CYBLE component
*  void* eventParams: A structure instance for corresponding event type. The
*                     list of event structure is described in the component
*                     datasheet.
*
* Return:
*  None
*
*******************************************************************************/
void StackEventHandler(uint32 event, void *eventParam)
{
    DebugCode("StackEventHandler++");
    
    /** Pointer to the write structure**/
    CYBLE_GATTS_WRITE_REQ_PARAM_T *writePTR; 
    unsigned int error = 0x0; /*No Error*/
    uint8 i = 0x0; 
    
    switch(event)
    {
        /* Mandatory events to be handled by Find Me Target design */
        case CYBLE_EVT_STACK_ON:
            /*This occurs as soon as the BLE is ON */
            DebugCode("BLE ON!! ADVERTISING :)");
            CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
        break;
            
        case CYBLE_EVT_GAP_DEVICE_DISCONNECTED:
            /* Start BLE advertisement for 30 seconds and update link
             * status on LEDs */
            DebugCode("BLE DISCONNECTED");
            CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
            DebugCode("Ble Restart!! ");
            disconnect_flag = 0x1; 
            break;

        case CYBLE_EVT_GAP_DEVICE_CONNECTED:
            /* BLE link is established */
            DebugCode("BONDING SUCCESS ");
            break;

        case CYBLE_EVT_GAPP_ADVERTISEMENT_START_STOP:
            if(CyBle_GetState() == CYBLE_STATE_DISCONNECTED)
            {
                /* Advertisement event timed out, go to low power
                 * mode (Stop mode) and wait for device reset
                 * event to wake up the device again */
                /*CySysPmSetWakeupPolarity(CY_PM_STOP_WAKEUP_ACTIVE_HIGH);*/
                disconnect_flag = 0x1; 
                CySysPmStop();
               
                /* Code execution will not reach here */
            }
            break;
        case CYBLE_EVT_GATTS_WRITE_REQ:
            DebugCode("SHREY :: Got a Write Request");
            writePTR = (CYBLE_GATTS_WRITE_REQ_PARAM_T *)eventParam; 
            if(writePTR != NULL)
            {
                if(CYBLE_TEST_TEST_CHAR_HANDLE == writePTR->handleValPair.attrHandle)
                {
                    DebugCode("Correct Char Handle");
                    if(writePTR->handleValPair.value.val != NULL)
                    {
                        if(ble_flag == 0)
                        {
                            DBG_PRINTF("Length = 0x%x \r \n", writePTR->handleValPair.value.len); 
                            ble_flag = 0x1; 
                            for(i = 0; i< writePTR->handleValPair.value.len; i++) 
                            {
                                msg_buffer[i] = writePTR->handleValPair.value.val[i];
                            }
                        }
                            
                    }
                }
            }
            error = CyBle_GattsWriteRsp(cyBle_connHandle);
            DBG_PRINTF("CYBLE_EVT_GATTS_WRITE_REQ Resp Error = %x \r \n", error);
            break;
            

        /* Other events that are generated by the BLE Component that
         * are not required for functioning of this design */
        /**********************************************************
        *                       General Events
        ***********************************************************/
        case CYBLE_EVT_HARDWARE_ERROR:    /* This event indicates that some internal HW error has occurred. */
            break;

        case CYBLE_EVT_HCI_STATUS:
            break;

        /**********************************************************
        *                       GAP Events
        ***********************************************************/
        case CYBLE_EVT_GAP_AUTH_REQ:
            break;

        case CYBLE_EVT_GAP_PASSKEY_ENTRY_REQUEST:
            break;

        case CYBLE_EVT_GAP_PASSKEY_DISPLAY_REQUEST:
            break;

        case CYBLE_EVT_GAP_AUTH_COMPLETE:

            break;
        case CYBLE_EVT_GAP_AUTH_FAILED:

            break;

        case CYBLE_EVT_GAP_ENCRYPT_CHANGE:
            break;

        case CYBLE_EVT_GAPC_CONNECTION_UPDATE_COMPLETE:
            break;

        /**********************************************************
        *                       GATT Events
        ***********************************************************/
        case CYBLE_EVT_GATT_CONNECT_IND:
            break;

        case CYBLE_EVT_GATT_DISCONNECT_IND:
            break;

        case CYBLE_EVT_GATTS_XCNHG_MTU_REQ:
            break;

        case CYBLE_EVT_GATTS_READ_CHAR_VAL_ACCESS_REQ:
            break;

        /**********************************************************
        *                       Other Events
        ***********************************************************/
        case CYBLE_EVT_PENDING_FLASH_WRITE:
            break;

        default:
            break;
    } /*Switch Case*/
    DebugCode("StackEventHandler--");
}

CY_ISR(WakeupIsrHandler)
{
//    static u8 sw_reg=0;
    /* Clear pending Interrupt */
    isr_Button_ClearPending();

    /* Clear pin Interrupt */
    Button_ClearInterrupt();
    
}


int main()
{
    //uint8 i = 0x0; 
    //uint8 temp_data = 0x0; 
    /*Enable the UART Debuger to get hold of data*/
    UART_Dbg_Start(); 
    
    /*Wait till the button is pressed */
    while(Button_Read() == 0u);
    CyDelay(500); 
    while(Button_Read() == 0u); 
    
    /*Process the button interrupts*/
    isr_Button_StartEx(WakeupIsrHandler);
    Button_ClearInterrupt();
    isr_Button_ClearPending(); 
    
    /*Unfreeze the GPIOS*/
    CySysPmUnfreezeIo(); 
    SET_DCDC_2_0V();
    
    CyGlobalIntEnable; /* Enable global interrupts. */
    
    DebugCode("SHREY Sleeve V1.0");
    DebugCode("*****************************************");
    DebugCode("Hello World");
    DebugCode("Starting BLE Processor Now");
    DebugCode("*****************************************");
    
    /** Start the BLE Processor Code Now **/ 
    CyBle_Start(StackEventHandler); 

#ifdef BLE_TEST
    while(1)
    {
       CyBle_ProcessEvents(); 
       /*For now if we have a disconnect just exit the loop 
         and turn off the BLE*/
       if(disconnect_flag == 0x1)
       {
            DebugCode("I recd a disconnect and I am about to close");
            break; 
       }
       if(ble_flag == 0x1)
       {
            DebugCode("Received a Valid data");
            DebugCode("Printing Received Characters"); 
#if 0 
            for(i=0; i < 4; i++)
            {
                temp_data= msg_buffer[i]; 
                DBG_PRINTF("0x%x \n",temp_data); 
            }
#endif 
            DBG_PRINTF("%s \n",msg_buffer); 
            /*clear the ble received flag*/
            ble_flag = 0x0; 
       }
    }
#endif 
    SET_DCDC_2_0V(); 
    EnableStop(); 
    return 0;
}

/* [] END OF FILE */
