# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Work\BLE_Proximity\BLE_Proximity01\BLE_Transfer.cydsn\BLE_Transfer.cyprj
# Date: Mon, 26 Feb 2018 07:17:33 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 83.333333333333329 -waveform {0 41.6666666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyLFCLK} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyECO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/eco}]]
create_clock -name {CyIMO} -period 83.333333333333329 -waveform {0 41.6666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 83.333333333333329 -waveform {0 41.6666666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 83.333333333333329 -waveform {0 41.6666666666667} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for C:\Work\BLE_Proximity\BLE_Proximity01\BLE_Transfer.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Work\BLE_Proximity\BLE_Proximity01\BLE_Transfer.cydsn\BLE_Transfer.cyprj
# Date: Mon, 26 Feb 2018 07:17:30 GMT
